version: '3'

services:
    
    php:
        build:
            context: ./docker/
            dockerfile: Dockerfile
        container_name: app_php
        restart: unless-stopped
        depends_on: 
            - mysql
        volumes: 
            - ./app:/var/www/html/app
        networks: 
            - my_network

    nginx:
        image: nginx:latest
        container_name: app_nginx
        volumes: 
            - ./app:/var/www/html/app
            - ./docker/nginx/log:/var/log/nginx
            - ./docker/nginx/config/app.conf:/etc/nginx/conf.d/app.conf
        ports:
            - "80:80"
        depends_on: 
            - php
        networks: 
            - my_network

    mysql:
        image: mysql:5.7
        container_name: app_mysql
        restart: unless-stopped
        ports:
            - 3309:3306
        volumes:
            - ./docker/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: app_db
            MYSQL_USER: app_user
            MYSQL_PASSWORD: 123456
        networks: 
            - my_network

    phpmyadmin:
        image: phpmyadmin
        container_name: app_phpmyadmin
        restart: unless-stopped
        ports:
            - 8282:80
        depends_on: 
            - mysql
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306
            - PMA_USER=root
            - PMA_PASSWORD=root
            - MYSQL_ROOT_PASSWORD=root
            - UPLOAD_LIMIT=64M
        networks: 
            - my_network

networks: 
    my_network: